{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.14.0-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "azure-resourcemanager-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "azure-resourcemanager-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "azure-resourcemanager-exporter.chart" . }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            backend:
              serviceName: {{ template "azure-resourcemanager-exporter.fullname" $ }}
              servicePort: {{ $.Values.service.port }}
    {{- end -}}
  {{- if $.Values.ingress.tls }}
  tls:
{{ toYaml $.Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
